import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Suspense } from "react";
import Loading from "./(pages)/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ padding: 20, background: "#eee" }}>
          {" "}
          <Image src={"/images/logo.jpg"} alt="logo" width={100} height={100} quality={100} unoptimized /> My App
        </header>

         <Suspense fallback={<Loading />}>
             <main>{children}</main>
         </Suspense>
        <footer style={{ padding: 20, background: "#eee" }}>© 2025</footer>
      </body>
    </html>
  );
}
